# Generated by Django 3.1.3 on 2020-12-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(db_index=True)),
                ('product_short_code', models.CharField(default=0, max_length=500, null=True)),
            ],
        ),
    ]
