# Generated by Django 3.1.3 on 2020-12-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmodel',
        ),
    ]
