# Generated by Django 3.1.3 on 2020-12-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyClass',
        ),
    ]
